import Head from "next/head";
import { Chrono } from "react-chrono";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div style={{ height: "500px", width: "100%" }}>
				<Chrono
					items={[
						{
							title: "Title 1",
							cardSubtitle: "Subtitle",
							timelineContent: (
								<div>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit.
										Nulla tincidunt eros sit amet sollicitudin consequat. Donec
										non nisl nec turpis commodo aliquam. Nunc mollis pretium
										volutpat. Praesent quam nunc, imperdiet vitae scelerisque
										eget, pharetra non leo. Phasellus gravida, ipsum vel
										sagittis aliquet, orci tortor vehicula lorem, eget feugiat
										sapien libero eu magna. Morbi scelerisque mauris ut leo
										sodales, eget fringilla orci lobortis. Duis convallis
										volutpat ornare. Aenean aliquam egestas lorem ut tristique.
										Sed vestibulum bibendum efficitur. Phasellus tempus nisl sed
										mauris pretium cursus. Curabitur in blandit dui. Nullam et
										maximus justo, nec accumsan tortor. Curabitur dolor leo,
										consectetur ut venenatis rutrum, luctus sed leo.
									</p>
									<p>
										Sed et sem at sem facilisis ultrices. Nullam pulvinar, risus
										quis condimentum consectetur, odio enim sagittis purus, nec
										interdum sem magna sit amet lorem. Mauris cursus tellus
										arcu, quis iaculis libero feugiat et. Mauris pretium nibh id
										risus sodales pharetra. Proin laoreet elementum odio, non
										maximus ligula vulputate ac. Mauris ultrices orci neque.
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
										commodo ex at metus interdum, sit amet commodo est sagittis.
										Cras sem lacus, egestas id purus in, sodales tristique
										magna. Quisque consectetur elit a pretium dignissim.
										Phasellus eu risus faucibus, luctus augue eget, sodales
										tellus. Donec iaculis quam eget pellentesque efficitur.
										Morbi mattis et nunc vel maximus. Aliquam pulvinar sem
										magna, id consectetur ex suscipit id. Proin tellus lacus,
										placerat vel magna sit amet, lacinia lobortis nulla.
										Suspendisse est lacus, facilisis ut volutpat in, gravida ac
										justo. Curabitur finibus in neque ac imperdiet.
									</p>
								</div>
							),
						},
					]}
					useReadMore
				/>
			</div>
		</>
	);
}
