import { Inter } from "@next/font/google";
import Head from "next/head";
import { Chrono } from "react-chrono";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div style={{ height: "500px", width: "100%" }}>
				<Chrono
					items={[
						{
							title: "Title 1",
							cardSubtitle: "Subtitle",
							timelineContent: (
								<div>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit.
										Nulla tincidunt eros sit amet sollicitudin consequat. Donec
										non nisl nec turpis commodo aliquam. Nunc mollis pretium
										volutpat. Praesent quam nunc, imperdiet vitae scelerisque
										eget, pharetra non leo. Phasellus gravida, ipsum vel
										sagittis aliquet, orci tortor vehicula lorem, eget feugiat
										sapien libero eu magna. Morbi scelerisque mauris ut leo
										sodales, eget fringilla orci lobortis. Duis convallis
										volutpat ornare. Aenean aliquam egestas lorem ut tristique.
										Sed vestibulum bibendum efficitur. Phasellus tempus nisl sed
										mauris pretium cursus. Curabitur in blandit dui. Nullam et
										maximus justo, nec accumsan tortor. Curabitur dolor leo,
										consectetur ut venenatis rutrum, luctus sed leo.
									</p>
								</div>
							),
						},
					]}
				/>
			</div>
		</>
	);
}
